sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=2002e6cb033fc09cb3a764c5d1622f756e0c2d2b61f0a62e51b8e38070cdff00
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
